### ISSUE TITLE
Pass filters

### ISSUE THREAD

**Issue by readelobdill** [lvbingru/react-native-gpuimage#1]
Hi! I've got this in my project and loading up images and am trying to pass through filters, can you give an example of how to properly pass GPUImagePixellateFilter and apply it to the image?

**Comment by readelobdill** [comment]
``` javascript
<GPUImageView
    filters={
        [
            {
                name: 'GPUImagePixellateFilter',
                params: {
                    fractionalWidthOfAPixel: 0.5
                }
            }
        ]
    }
/>
```

**Comment by alexandergunnarson** [comment]
Thanks for providing the only documentation for this great but (as of yet) undocumented library!
